### PR TITLE
Made the bot even better

### PR DESCRIPTION
**Pull request by nomyTx**

### CODE REVIEW

**Comment by nitin-ojha1** [comment]
since when did i harras women by the way? you werent even in alyxia's and my dms. any proof?, still want to make this shit public argument?

**Comment by smartfrigde** [comment]
Alyxia is based

**Comment by kekkodance** [comment]
> 
> 
> since when did i harras women by the way? you werent even in alyxia's and my dms. any proof?, still want to make this shit public argument?

woman harrasser
_sex_

**Comment by nitin-ojha1** [comment]
> Alyxia is based 

yeah i guess

**Comment by kekkodance** [comment]
> 
> 
> > Alyxia is based
> 
> yeah i guess

you need to stop harrassing the women and fetishizing lesbians

**Comment by keanuplayz** [comment]
e

**Pull request closed without merging**
